import { defineCollection, z } from "astro:content";

const urlOrPath = z
	.string()
	.refine(
		(v) => v.startsWith("/") || /^https?:\/\//i.test(v) || v === "",
		{ message: "Must be an absolute site path (/img.png) or http(s) URL. Or leave empty." },
	);

export const apps = defineCollection({
	type: "content",
	schema: z.object({
		title: z.string(),
		tagline: z.string(),
		description: z.string(),

		// Allows local icon or URL; optional since we use a placeholder
		icon: urlOrPath.optional(),

		// Stores
		playUrl: z.string().url(),
		appStoreUrl: z.string().url().optional(),

		category: z.string().default("Tools"),
		tags: z.array(z.string()).default([]),

		// i18n
		locale: z.enum(["en", "es", "pt"]).default("en"),

		price: z.string().default("Free"),
		version: z.string().optional(),

		// Stores ISO yyyy-mm-dd; if a string arrives, we coerce and normalize
		lastUpdated: z
			.string()
			.optional()
			.transform((v) => v ?? new Date().toISOString().slice(0, 10)),

		// In the UI you display "1K+"; here it's better to store as a flexible string
		downloads: z.union([z.string(), z.number()]).default(0).transform(String),

		// 0-5 optional (the form already has it)
		rating: z.number().min(0).max(5).optional(),
		ratingCount: z.number().int().optional(),

		// Beta / early access apps
		beta: z.boolean().default(false),
		betaGroupUrl: z.string().url().optional(),

		// Absolute site paths or URLs
		screenshots: z.array(urlOrPath).default([]),
	}),
});

const blog = defineCollection({
	type: "content",
	schema: z.object({
		title: z.string(),
		description: z.string(),
		// Stable cross-locale identifier shared by translations of the same post.
		// When present on multiple posts, the blog page resolves siblings and emits
		// correct hreflang links (and language-switcher URLs) per locale.
		translationKey: z.string().optional(),
		publishedAt: z.coerce.date(),
		updatedAt: z.coerce.date().optional(),
		author: z.string().default("FusionCore Apps"),
		tags: z.array(z.string()).default([]),
		// In-page hero image (real screenshots, product shots). Also the fallback
		// og:image when `ogImage` is absent.
		image: z.string().optional(),
		// Social/SERP card only — never rendered in-page. Generated by
		// scripts/og_hero_v4.py at 1200x630 into public/images/blog/<locale>/<slug>.png.
		// NOTE: it must NOT live under public/blog/ — that path collides with the
		// /blog/[slug] route and the asset never renders.
		// Kept separate from `image` so a post can show a real screenshot as its
		// hero while still sharing a branded, headline-bearing card.
		ogImage: z.string().optional(),
		featured: z.boolean().default(false),
		// Q&As mirrored by a visible FAQ section in the post body (Google requires
		// on-page parity); rendered as FAQPage JSON-LD by BlogJsonLd.astro.
		faq: z
			.array(z.object({ question: z.string(), answer: z.string() }))
			.optional(),
	}),
});

const legal = defineCollection({
	type: "content",
	schema: z.object({
		title: z.string(),
		updatedAt: z.string(),
	}),
});

const comparisons = defineCollection({
	type: "content",
	schema: z.object({
		title: z.string(),
		description: z.string(),
		competitorName: z.string(),
		competitorSlug: z.string(),
		translationKey: z.string(),
		updatedAt: z.string(),
		cartwiseRating: z.number().optional(),
		cartwiseReviewCount: z.string().optional(),
		competitorRating: z.number().optional(),
		competitorReviewCount: z.string().optional(),
		competitorIconEmoji: z.string().default("📱"),
		competitorIcon: urlOrPath.optional(),
		heroDeck: z.string(),
		introParagraphs: z.array(z.string()),
		quickTable: z.array(z.object({ category: z.string(), cartwise: z.string(), competitor: z.string() })),
		featureRows: z.array(z.object({ feature: z.string(), cartwise: z.string(), competitor: z.string() })),
		cartwiseGood: z.array(z.string()),
		cartwiseBad: z.array(z.string()),
		competitorGood: z.array(z.string()),
		competitorBad: z.array(z.string()),
		midVerdict: z.string(),
		finalVerdict: z.array(z.string()),
		relatedSlugs: z.array(z.string()).default([]),
	}),
});

export const collections = { apps, blog, legal, comparisons };
