#!/bin/bash

# Verify the operating system
if [ "$OSTYPE" = "msys" ] || [ "$OSTYPE" = "win32" ]; then
  # If it's Windows, run npx.cmd lint-staged
  echo "🔍 Running lint checks before commit..."
  npx.cmd lint-staged
  status=$? # Capture the exit code
else
  # If it's not Windows, try to run npx lint-staged
  if command -v npx 2> /dev/null; then
    echo "🔍 Running lint checks before commit..."
    npx lint-staged
    status=$? # Capture the exit code
  else
    echo "❌ The 'npx' command was not found, install 'npx' and try again."
    exit 1
  fi
fi

# Check the status and display an appropriate message
if [ $status -ne 0 ]; then
  echo "❌ Lint-staged failed with errors or warnings:"
  echo "🔨 Check the output above for more details."
  exit 1
else
  echo "✅ All lint checks passed. Proceeding with commit..."
  exit 0
fi